=== berachain/metadata/schemas/tokens.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string",
      "pattern": "^\\.\\./.+\\.schema\\.json$"
    },
    "name": {
      "type": "string",
      "minLength": 1
    },
    "logoURI": {
      "type": "string",
      "pattern": "^(https://imagedelivery\\.net/qNj7Q3MCke89zoKzav7eDQ/(tokens/(default|0x[0-9a-fA-F]{40})\\.(png|jpg|jpeg)|validators/0x[0-9a-fA-F]{96}\\.(png|jpg|jpeg)|vaults/0x[0-9a-fA-F]{40}\\.(png|jpg|jpeg)|protocols/[a-z0-9-]+\\.(png|jpg|jpeg))/public)$"
    },
    "tags": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "minLength": 1
          },
          "description": {
            "type": "string",
            "minLength": 1
          }
        },
        "required": ["name", "description"],
        "additionalProperties": false
      }
    },
    "tokens": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "address": {
            "type": "string",
            "pattern": "^0x[a-fA-F0-9]{40}$"
          },
          "chainId": {
            "type": "integer"
          },
          "name": {
            "type": "string"
          },
          "symbol": {
            "type": "string"
          },
          "decimals": {
            "type": "integer"
          },
          "logoURI": {
            "type": "string",
            "pattern": "^(https://imagedelivery\\.net/qNj7Q3MCke89zoKzav7eDQ/(tokens/(default|0x[0-9a-fA-F]{40})\\.(png|jpg|jpeg)|validators/0x[0-9a-fA-F]{96}\\.(png|jpg|jpeg)|vaults/0x[0-9a-fA-F]{40}\\.(png|jpg|jpeg)|protocols/[a-z0-9-]+\\.(png|jpg|jpeg))/public)$"
          },
          "base64": {
            "type": "string"
          },
          "tags": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "required": ["address", "chainId", "name", "symbol", "decimals"]
      },
      "minItems": 1
    }
  },
  "required": ["name", "logoURI", "tags", "tokens", "$schema"],
  "additionalProperties": false
}

=== berachain/metadata/src/tokens/bepolia.json
{
  "$schema": "../../schemas/tokens.schema.json",
  "name": "Berachain Bepolia Token List",
  "logoURI": "https://imagedelivery.net/qNj7Q3MCke89zoKzav7eDQ/tokens/default.png/public",
  "tags": {
    "stablecoin": {
      "name": "Stablecoin",
      "description": "Tokens that are fixed to an external asset, e.g. the US dollar"
    },
    "featured": {
      "name": "Featured",
      "description": "Tokens that are featured"
    }
  },
  "tokens": [
    {
      "chainId": 80069,
      "address": "0x6969696969696969696969696969696969696969",
      "symbol": "WBERA",
      "name": "Wrapped Berachain Token",
      "decimals": 18,
      "logoURI": "https://imagedelivery.net/qNj7Q3MCke89zoKzav7eDQ/tokens/0x6969696969696969696969696969696969696969.png/public",
      "tags": ["featured"],
      "extensions": {
        "coingeckoId": "berachain-bera",
        "pythPriceId": "0x962088abcfdbdb6e30db2e340c8cf887d9efb311b1f2f17b155a63dbb6d40265"
      }
    },
    {
      "chainId": 80069,
      "address": "0x0000000000000000000000000000000000000000",
      "symbol": "BERA",
      "name": "Berachain Token",
      "decimals": 18,
      "logoURI": "https://imagedelivery.net/qNj7Q3MCke89zoKzav7eDQ/tokens/0x0000000000000000000000000000000000000000.png/public",
      "tags": ["featured"],
      "extensions": {
        "coingeckoId": "berachain-bera",
        "pythPriceId": "0x962088abcfdbdb6e30db2e340c8cf887d9efb311b1f2f17b155a63dbb6d40265"
      }
    },
    {
      "chainId": 80069,
      "address": "0x656b95E550C07a9ffe548bd4085c72418Ceb1dba",
      "symbol": "BGT",
      "name": "Bera Governance Token",
      "decimals": 18,
      "logoURI": "https://imagedelivery.net/qNj7Q3MCke89zoKzav7eDQ/tokens/0x656b95e550c07a9ffe548bd4085c72418ceb1dba.png/public",
      "tags": ["featured"]
    },
    {
      "chainId": 80069,
      "address": "0xFCBD14DC51f0A4d49d5E53C2E0950e0bC26d0Dce",
      "symbol": "HONEY",
      "name": "Honey",
      "decimals": 18,
      "logoURI": "https://imagedelivery.net/qNj7Q3MCke89zoKzav7eDQ/tokens/0xfcbd14dc51f0a4d49d5e53c2e0950e0bc26d0dce.png/public",
      "tags": ["stablecoin", "featured"],
      "extensions": {
        "pythPriceId": "0xf67b033925d73d43ba4401e00308d9b0f26ab4fbd1250e8b5407b9eaade7e1f4"
      }
    },
    {
      "chainId": 80069,
      "address": "0x6e8d0eCfCE5c2b7587263923e23d141F6364c7f9",
      "symbol": "bbUSDC",
      "name": "bbUSDC",
      "logoURI": "https://imagedelivery.net/qNj7Q3MCke89zoKzav7eDQ/tokens/0x6e8d0ecfce5c2b7587263923e23d141f6364c7f9.png/public",
      "decimals": 18,
      "tags": ["stablecoin", "featured"],
      "extensions": {
        "coingeckoId": "usd-coin",
        "pythPriceId": "0xeaa020c61cc479712813461ce153894a96a6c00b21ed0cfc2798d1f9a9e9c94a"
      }
    },
    {
      "chainId": 80069,
      "address": "0xe0037233a4a21c6334CFa67895A4BeaDc87B2c40",
      "symbol": "bbBYUSD",
      "name": "bbBYUSD",
      "logoURI": "https://imagedelivery.net/qNj7Q3MCke89zoKzav7eDQ/tokens/0xe0037233a4a21c6334cfa67895a4beadc87b2c40.png/public",
      "decimals": 18,
      "tags": ["stablecoin", "featured"],
      "extensions": {
        "coingeckoId": "paypal-usd",
        "pythPriceId": "0xc1da1b73d7f01e7ddd54b3766cf7fcd644395ad14f70aa706ec5384c59e76692"
      }
    },
    {
      "chainId": 80069,
      "address": "0x75A226792e574918855740eBE24aD2f06D4d0Fb9",
      "symbol": "USD₮0",
      "name": "Tether USD Coin",
      "decimals": 6,
      "logoURI": "https://imagedelivery.net/qNj7Q3MCke89zoKzav7eDQ/tokens/0x75a226792e574918855740ebe24ad2f06d4d0fb9.png/public",
      "tags": ["stablecoin", "featured"],
      "extensions": {
        "coingeckoId": "tether",
        "pythPriceId": "0x2b89b9dc8fdf9f34709a5b106b472f0f39bb6ca9ce04b0fd7f2e971688e2e53b"
      }
    },
    {
      "chainId": 80069,
      "address": "0xC8d68e161227b180c5046E706E0A6d8ab78D83C5",
      "symbol": "bbINC1",
      "name": "bbINC1",
      "decimals": 18,
      "tags": [],
      "extensions": {
        "pythPriceId": "0xeaa020c61cc479712813461ce153894a96a6c00b21ed0cfc2798d1f9a9e9c94a"
      }
    },
    {
      "chainId": 80069,
      "address": "0xA36E29dd481f80F331931f1944E5Aa743e074c85",
      "symbol": "bbINC2",
      "name": "bbINC2",
      "decimals": 18,
      "tags": [],
      "extensions": {
        "pythPriceId": "0xeaa020c61cc479712813461ce153894a96a6c00b21ed0cfc2798d1f9a9e9c94a"
      }
    },
    {
      "chainId": 80069,
      "address": "0xf0063bac3Bd6a88049dDE2422365aaFd87D49054",
      "symbol": "bbINC3",
      "name": "bbINC3",
      "decimals": 18,
      "tags": [],
      "extensions": {
        "pythPriceId": "0xeaa020c61cc479712813461ce153894a96a6c00b21ed0cfc2798d1f9a9e9c94a"
      }
    },
    {
      "chainId": 80069,
      "address": "0x1DB94dA7E7Af8529878053559552CFA8797f447B",
      "symbol": "bbINC4",
      "name": "bbINC4",
      "decimals": 18,
      "tags": [],
      "extensions": {
        "pythPriceId": "0xeaa020c61cc479712813461ce153894a96a6c00b21ed0cfc2798d1f9a9e9c94a"
      }
    },
    {
      "chainId": 80069,
      "address": "0xF93CD4C23398A827B70A5994C21C5e8023394dad",
      "symbol": "bbINC5",
      "name": "bbINC5",
      "decimals": 18,
      "tags": [],
      "extensions": {
        "pythPriceId": "0xeaa020c61cc479712813461ce153894a96a6c00b21ed0cfc2798d1f9a9e9c94a"
      }
    },
    {
      "chainId": 80069,
      "address": "0xFDD764D4Afd1F378B1bA1E56f477C4C4585B15D8",
      "symbol": "bbINC6",
      "name": "bbINC6",
      "decimals": 18,
      "tags": [],
      "extensions": {
        "pythPriceId": "0xeaa020c61cc479712813461ce153894a96a6c00b21ed0cfc2798d1f9a9e9c94a"
      }
    },
    {
      "chainId": 80069,
      "address": "0xE2c84758017616bCC4563D569d2D4d6B3e379D7c",
      "symbol": "bbINC7",
      "name": "bbINC7",
      "decimals": 18,
      "tags": [],
      "extensions": {
        "pythPriceId": "0xeaa020c61cc479712813461ce153894a96a6c00b21ed0cfc2798d1f9a9e9c94a"
      }
    },
    {
      "chainId": 80069,
      "address": "0x118d2ceee9785eaf70c15cd74cd84c9f8c3eec9a",
      "symbol": "sWBERA",
      "name": "Staked WBERA",
      "logoURI": "https://imagedelivery.net/qNj7Q3MCke89zoKzav7eDQ/tokens/0x118d2ceee9785eaf70c15cd74cd84c9f8c3eec9a.png/public",
      "decimals": 18,
      "tags": ["featured"]
    },
    {
      "chainId": 80069,
      "address": "0x150f4bF02AfE36e19637ae0bd0D426c464fC1e7a",
      "name": "USDe",
      "symbol": "USDe",
      "decimals": 18,
      "logoURI": "https://imagedelivery.net/qNj7Q3MCke89zoKzav7eDQ/tokens/0x150f4bf02afe36e19637ae0bd0d426c464fc1e7a.png/public",
      "extensions": {
        "coingeckoId": "ethena-usde",
        "pythPriceId": "0x6ec879b1e9963de5ee97e9c8710b742d6228252a5e2ca12d4ae81d7fe5ee8c5d"
      }
    }
  ]
}
