=== berachain/metadata/schemas/vaults.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string",
      "pattern": "^\\.\\./.+\\.schema\\.json$"
    },
    "name": {
      "type": "string",
      "minLength": 1
    },
    "categories": {
      "type": "array",
      "minLength": 1,
      "items": {
        "type": "object",
        "required": ["slug", "name"],
        "properties": {
          "slug": {
            "type": "string",
            "minLength": 1
          },
          "name": {
            "type": "string",
            "minLength": 1,
            "description": "For UI purposes, this might change in the future."
          },
          "description": {
            "type": "string",
            "minLength": 1,
            "description": "This is a description of the category. It is intended to be used for documentation purposes."
          },
          "subcategories": {
            "type": "array",
            "items": {
              "type": "object",
              "required": ["slug"],
              "properties": {
                "slug": {
                  "type": "string",
                  "minLength": 1
                }
              }
            }
          }
        }
      }
    },
    "protocols": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "minLength": 1
          },
          "logoURI": {
            "type": "string",
            "pattern": "^(https://raw.githubusercontent.com/berachain/metadata/[^\\s]+|https://(assets|coin-images).coingecko.com/[^\\s]+|https://res.cloudinary.com/duv0g402y/[^\\s]+|https://imagedelivery\\.net/qNj7Q3MCke89zoKzav7eDQ/(tokens/0x[0-9a-fA-F]{40}\\.(png|jpg|jpeg)|validators/0x[0-9a-fA-F]{96}\\.(png|jpg|jpeg)|vaults/0x[0-9a-fA-F]{40}\\.(png|jpg|jpeg)|protocols/[a-z0-9-]+\\.(png|jpg|jpeg))/public)$"
          },
          "url": {
            "type": "string",
            "pattern": "^(https://[^\\s]+)$"
          },
          "description": {
            "type": "string"
          },
          "tags": {
            "type": "array",
            "description": "This is an array of tags. Currently used for UI purposes.",
            "items": {
              "type": "string"
            }
          }
        },
        "required": ["name", "url", "description", "logoURI"]
      }
    },
    "vaults": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "stakingTokenAddress": {
            "type": "string",
            "pattern": "^0x[a-fA-F0-9]{40}$"
          },
          "vaultAddress": {
            "type": "string",
            "pattern": "^0x[a-fA-F0-9]{40}$"
          },
          "name": {
            "type": "string",
            "minLength": 1
          },
          "action": {
            "type": "string",
            "description": "This is how the vault will be called on BeraHub. It should be a verb (e.g. Stake into...).",
            "minLength": 1
          },
          "protocol": {
            "type": "string",
            "minLength": 1
          },
          "logoURI": {
            "type": "string",
            "pattern": "^(https://raw.githubusercontent.com/berachain/metadata/[^\\s]+|https://(assets|coin-images).coingecko.com/[^\\s]+|https://res.cloudinary.com/duv0g402y/[^\\s]+|https://imagedelivery\\.net/qNj7Q3MCke89zoKzav7eDQ/(tokens/0x[0-9a-fA-F]{40}\\.(png|jpg|jpeg)|validators/0x[0-9a-fA-F]{96}\\.(png|jpg|jpeg)|vaults/0x[0-9a-fA-F]{40}\\.(png|jpg|jpeg)|protocols/[a-z0-9-]+\\.(png|jpg|jpeg))/public)$"
          },
          "url": {
            "type": "string",
            "pattern": "^(https://[^\\s]+)$"
          },
          "categories": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "$comment": "This is an array of categories. It must have exactly one item. It's an array for future proofing.",
            "minItems": 1,
            "maxItems": 1
          },
          "description": {
            "type": "string"
          }
        },
        "required": [
          "stakingTokenAddress",
          "vaultAddress",
          "name",
          "protocol",
          "url",
          "categories"
        ]
      }
    }
  },
  "additionalProperties": false,
  "required": ["name", "protocols", "vaults", "$schema", "categories"]
}

=== berachain/metadata/src/vaults/bepolia.json
{
  "$schema": "../../schemas/vaults.schema.json",
  "name": "Berachain Bepolia Reward Vault List",
  "protocols": [
    {
      "name": "HUB",
      "logoURI": "https://imagedelivery.net/qNj7Q3MCke89zoKzav7eDQ/protocols/hub.png/public",
      "url": "https://bepolia.hub.berachain.com",
      "description": "Swap a variety of tokens effortlessly on our decentralized platform. Provide liquidity to pools and earn BGT rewards.",
      "tags": ["platform"]
    }
  ],
  "categories": [
    {
      "slug": "defi",
      "name": "DeFi"
    },
    {
      "slug": "foundation",
      "name": "Foundation",
      "description": "This is a testnet-only category. It includes vaults that the Berachain Foundation owns to maintain the testnet."
    }
  ],
  "vaults": [
    {
      "stakingTokenAddress": "0xDa94d2bfc516f1963C4c36f390a803D544688f71",
      "vaultAddress": "0x57abe4e0c59a650a7042e18493179dd5b91a3f61",
      "name": "Bepolia Foundation Vault #1",
      "protocol": "HUB",
      "categories": ["foundation"],
      "url": "https://bepolia.hub.berachain.com/vaults/0x57abe4e0c59a650a7042e18493179dd5b91a3f61",
      "description": "Bribes automation, Owned by BD team",
      "logoURI": "https://imagedelivery.net/qNj7Q3MCke89zoKzav7eDQ/vaults/0x57abe4e0c59a650a7042e18493179dd5b91a3f61.png/public"
    },
    {
      "stakingTokenAddress": "0xA9d09e1Bd86bBAFeac4020099207eE23549618B0",
      "vaultAddress": "0xae461ea8238df1bd63B3f93b0EF7da1A56De2f91",
      "name": "Bepolia Foundation Vault #2",
      "protocol": "HUB",
      "categories": ["foundation"],
      "url": "https://bepolia.hub.berachain.com/vaults/0xae461ea8238df1bd63B3f93b0EF7da1A56De2f91",
      "description": "Bribes automation, Owned by BD team",
      "logoURI": "https://imagedelivery.net/qNj7Q3MCke89zoKzav7eDQ/vaults/0xae461ea8238df1bd63b3f93b0ef7da1a56de2f91.png/public"
    },
    {
      "stakingTokenAddress": "0x5bA554fA6faDc5583eD99d09E0545dB4bC9f994d",
      "vaultAddress": "0x45450D1E3bfd42E224976a7a263F7e59AB9607C8",
      "name": "Bepolia Foundation Vault #3",
      "protocol": "HUB",
      "categories": ["foundation"],
      "url": "https://bepolia.hub.berachain.com/vaults/0x45450D1E3bfd42E224976a7a263F7e59AB9607C8",
      "description": "Bribes automation, Owned by BD team",
      "logoURI": "https://imagedelivery.net/qNj7Q3MCke89zoKzav7eDQ/vaults/0x45450d1e3bfd42e224976a7a263f7e59ab9607c8.png/public"
    },
    {
      "stakingTokenAddress": "0xe5C337e10089246afE8DA5752BB1777613F70aa9",
      "vaultAddress": "0x3bcED9bC841a862716d58560c07480c203e61912",
      "name": "Bepolia Foundation Vault #4",
      "protocol": "HUB",
      "categories": ["foundation"],
      "url": "https://bepolia.hub.berachain.com/vaults/0x3bcED9bC841a862716d58560c07480c203e61912",
      "description": "Owned by Frontend Team",
      "logoURI": "https://imagedelivery.net/qNj7Q3MCke89zoKzav7eDQ/vaults/0x3bced9bc841a862716d58560c07480c203e61912.png/public"
    },
    {
      "stakingTokenAddress": "0x9d323a87597667d7373CF9C2F758a29896f6496A",
      "vaultAddress": "0x668b25f09D1f505b774bb5F686874c401EE22730",
      "name": "Bepolia Foundation Vault #5",
      "protocol": "HUB",
      "categories": ["foundation"],
      "url": "https://bepolia.hub.berachain.com/vaults/0x668b25f09D1f505b774bb5F686874c401EE22730",
      "logoURI": "https://imagedelivery.net/qNj7Q3MCke89zoKzav7eDQ/vaults/0x668b25f09d1f505b774bb5f686874c401ee22730.png/public"
    }
  ]
}
